name: nile_club
description: Nile club app.
publish_to: 'none' 
version: 1.0.1+10

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  flutter_svg: ^0.22.0
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  gap: ^2.0.0
  dio: ^4.0.6
  flutter_spinkit: ^5.1.0
  qr_flutter: ^4.0.0
  screenshot: ^1.2.3
  url_launcher: ^6.1.6
  image_gallery_saver: '^1.7.1'
  permission_handler: ^10.0.0
  webview_flutter: ^3.0.4
  jiffy: ^5.0.0
  image_picker: ^0.8.5+3
  lottie: ^1.0.0
  restart_app: ^1.1.0+1
  liquid_pull_to_refresh: ^3.0.1
  simple_animations: ^3.0.0+2
  qr_code_scanner: ^1.0.1
  internet_connection_checker: ^0.0.1+4
  rename: ^2.0.1
  dropdown_button2: ^1.8.9
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.2
  local_auth: ^2.1.2
  cached_network_image: ^3.0.0
  package_info_plus: ^3.0.2
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo3.png"
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          # weight: 600
    - family: Roboto_Slab
      fonts:
        - asset: assets/fonts/Roboto_Slab/RobotoSlab-Regular.ttf        
        - asset: assets/fonts/Roboto_Slab/RobotoSlab-Bold.ttf     
          weight: 700      
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
